# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1de41d9d8985dab5ee3cae6a5eae92521cad79c1eb97438bd3fb2c22df306bbf900e0745cdf9d0d8a5fdb60b676ce5da5926ede231ebcbc7fead6bebc0a23fe2

test:
  secret_key_base: 835a1125527995946a31f29969a976e166a85f0640849fa463baefdda6f40452e309899b8591bcfc2e89ff2112a5d1ce8cf95e6e02a562ff50b52a8e0a2b0b4b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
